# Generated by Django 4.2.14 on 2024-09-11 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_max_price_alter_product_min_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
    ]
