# Generated by Django 4.2.14 on 2024-09-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_items",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
