# Generated by Django 4.2.14 on 2024-10-03 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_user_id",
        ),
    ]
