# Generated by Django 4.2.14 on 2024-09-06 07:28

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseUserInfo",
            fields=[
                ("photo", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=250)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "second_phone_number",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "building_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "apartment_number",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
