# Generated by Django 4.2.14 on 2024-09-23 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
    ]
