# Generated by Django 4.2.14 on 2024-10-02 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coupon", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_active": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="used_coupons", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["is_active"],
                name="coupon_is_active_idx",
            ),
        ),
    ]
