# Generated by Django 4.2.14 on 2024-09-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0002_alter_coupon_options_coupon_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="coupon",
            name="coupon_is_active_idx",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
